@startuml 6-3-2
[*] --> メニュー

メニュー --> 予約と確認 : 予約をする
メニュー --> メニュー : 画面リロード

予約と確認 --> あなたの順番 : 登録ボタンを押す
予約と確認 --> あなたの順番 : 確認ボタンを押す
予約と確認 --> メニュー : 取消ボタンを押す

あなたの順番 --> 予約と確認 : 画面リロード
あなたの順番 --> 今の順番 : 画面リロード

今の順番 --> 今の順番 : 順番の更新

@enduml
