@startuml aaa
left to right direction

actor 利用者 as user
actor ホテル従業員 as staff
actor ホテル管理者 as admin

rectangle システム {

(ログイン) --> (部屋を予約) : 利用者
(ログイン) --> (空室状況の入力) : ホテル従業員
(ログイン) --> (予約の集計) : ホテル管理者

(会員登録) --> (ログイン) : 利用者

(空室状況を閲覧) --> (会員登録) : 利用者
(キャンペーン情報を閲覧) --> (会員登録) : 利用者
(空室状況を閲覧) --> (ログイン) : 利用者、ホテル従業員、ホテル管理者
(キャンペーン情報を閲覧) --> (ログイン) : 利用者、ホテル従業員、ホテル管理者

}

user --> (空室状況を閲覧)
user --> (キャンペーン情報を閲覧)
staff --> (ログイン)
admin --> (ログイン)

@enduml