@startuml 演習6-3-1

actor ユーザー as ユーザー
actor 看護士 as 看護士

rectangle システム {
  ユーザー --> (メニュー)
  ユーザー --> (予約と確認)
  ユーザー --> (取消)
  ユーザー --> (あなたの順番)
  看護士 --> (現在の順番)

  (予約と確認) --> (あなたの順番)
  (予約と確認) --> (メニュー)
  (取消) --> (メニュー)
  (あなたの順番) --> (メニュー)
  (現在の順番) --> (メニュー)
}

@enduml
