@startuml 演習3-2
class 医師 {
    - 名前: 文字列
    - 専門: 専門科目
    - 医局: 医局
}
class 患者 {
    - 名前: 文字列
    - 担当医: 医師
}
class 医局 {
    - 名前: 文字列
    - 医師リスト: 医師[]
}
class 診療記録 {
    - 日付: 日付
    - 記録: 文字列
    - 患者: 患者
    - 医師: 医師
}

enum 専門科目 {
    外科
    内科
    小児科
}

医師 *--o 患者
医師 o--o 医局
診療記録 *-- 患者
診療記録 *-- 医師
@enduml
