@startuml 演習4-5
actor 会員

activate 会員

会員 -> 商品検索画面 : 商品検索リクエスト送信

activate 商品検索画面

商品検索画面 -> 商品情報検索システム : 検索リクエスト送信

activate 商品情報検索システム

商品情報検索システム -> データベース : 商品情報検索リクエスト送信

activate データベース

データベース -> 商品情報検索システム : 商品情報検索結果応答送信

deactivate データベース

商品情報検索システム -> 商品検索画面 : 商品情報検索結果応答送信

deactivate 商品情報検索システム

商品検索画面 -> 会員 : 商品情報検索結果表示

deactivate 商品検索画面

deactivate 会員
@enduml
