@startuml 6-4-1
class 自動販売機 {
  - ボタン[10]
  - 料金装置
  - ベンダー装置
}

class ボタン {
  - ドリンク種別
  + ドリンク選択()
}

class 料金装置 {
  + お金受け取り()
}

class ベンダー装置 {
  - ドリンク[10]
  + ドリンク補充()
}

自動販売機 --> ボタン
自動販売機 --> 料金装置
自動販売機 --> ベンダー装置
ボタン --> 料金装置
ベンダー装置 --> ドリンク

@enduml
