@startuml ホテルと利用者と部屋と予約
class 利用者 {
    - 名前
    - 住所
    - 電話番号
}

class ホテル {
    - 部屋: 部屋[*]
    + 登録会員: 利用者[*]
}

class 部屋 {
    - タイプ
    - 価格
    - キャンペーン価格
    + 予約情報: 予約[*]
}

class 予約 {
    - チェックイン日
    - 滞在期間
    - 値段
}

利用者 --> ホテル: 登録会員
利用者 --> 予約: 予約
予約 --> 部屋: 予約情報
ホテル --> 部屋: 部屋
@enduml
