@startuml 演習7-3
|顧客|
start
:案内を依頼する;
|給仕|
:テーブルに案内する;
:メニューを渡す;
-> メニュー;
|顧客|
:注文を決める;
-> 注文;
|給仕|
fork
:注文を受ける;
fork again
:伝票を書く;
forkend
:料理人に注文を伝える;
-> 注文;
|料理人|
:注文を受ける;
:料理を作る;
-> 料理;
|給仕|
:料理を運ぶ;
:伝票を渡す;
-> 伝票;
|顧客|
:料理を食べる;
-> 伝票;
:代金を払う;
|給仕|
stop
@enduml