@startuml 演習6-5-2

left to right direction
actor ユーザー
actor ライントレーサー
actor 光センサー
actor 右モータ
actor 左モータ

rectangle システム {
ユーザー --> (ライントレーサーの起動)
ユーザー --> (ライントレーサーの停止)
ユーザー --> (ラインの状態確認)
光センサー --> (暗いラインの検出)
光センサー --> (明るいラインの検出)
右モータ --> (右旋回の開始)
左モータ --> (左旋回の開始)
ライントレーサー --> 光センサー
ライントレーサー --> 右モータ
ライントレーサー --> 左モータ
}
@enduml