@startuml 演習7-1

|ユーザ| as ユーザ

start
:ユーザ名を入力する;
:パスワードを入力する;
if (認証成功？) then (はい)
  :予約を行う;
else (いいえ)
  :ユーザ名とパスワードを再入力する;
  repeat
    :ユーザ名を入力する;
    :パスワードを入力する;
  repeat while (認証成功？)
  :予約を行う;
endif
:予約完了;
stop

@enduml