@startuml 6-4-2
actor 客 as Client
actor ベンダー as Vendor

Client --> (ドリンク選択)
Client --> (お金投入)
Client --> (ドリンク受け取り)

Vendor --> (ドリンク補充)
Vendor --> (料金回収)

(ドリンク選択) --> (お金投入)
(お金投入) --> (ドリンク受け取り)
(ドリンク受け取り) --> (ドリンク補充)
(ドリンク補充) --> (料金回収)

@enduml
